defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  #mongoid defaults for configurable settings
  autocreate_indexes: false
  #allow_dynamic_fields: true #deprecated?
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3

development:
  <<: *defaults
  database: ruud_showcase_development

test:
  <<: *defaults
  database: ruud_showcase_test

cucumber:
    <<: *TEST

# set these environment variables on your prod server
production:
    uri: <%= ENV['MONGOHQ_URL'] %>